import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist } from 'next/font/google'
import "./globals.css";
import { ThemeProvider } from "@/components/custom/theme.provider";
import { Analytics } from "@vercel/analytics/next"

const fontLora = localFont({
  src: [
    {
      path: "../fonts/Lora-Bold.ttf",
      weight: "400",
      style: "bold",
    },
    {
      path: "../fonts/Lora-BoldItalic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../fonts/Lora-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-lora",
  display: "swap",
  preload: true,
});

const fontGeist = Geist({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-geist',
  display: 'swap',
  preload: true,
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontGeist.variable} ${fontLora.variable} antialiased bg-[#FAFAFA]`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="light"
            forcedTheme="light"
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
          <Analytics/>
      </body>
    </html>
  );
}
